### ISSUE TITLE
Build Counter includes not available buildings

### ISSUE THREAD

**Issue by VShkaberda** [CheckiO/eoc-timeline#10]
If building can't be built because of Command center level, it isn't counted. Though if building can't be built because of lack of Energy , it is counted.
![Total](https://user-images.githubusercontent.com/11950122/61176474-2c7ee000-a5ca-11e9-97c6-73cdfb15e4eb.PNG)
![Support](https://user-images.githubusercontent.com/11950122/61176476-3b659280-a5ca-11e9-8e3f-84efbcf9053d.PNG)

**Comment by CheckiO** [comment]
The counter shows you available building on current CC level, so buildings that are required more energy to build should be included as well.
