### ISSUE TITLE
Research cards quantity in chests is incorrect

### ISSUE THREAD

**Issue by EugeneLukovkin** [CheckiO/eoc-timeline#4]
1. Open a chest
2. Check the reward with some number of the research cards 
3. Check the inventory 
4. Only one card was added, despite the previous number

![Screenshot from 2019-05-27 13-01-06](https://user-images.githubusercontent.com/51169245/58572083-b0138600-8243-11e9-8c03-57c8bdb90733.png)
![Screenshot from 2019-05-27 13-01-15](https://user-images.githubusercontent.com/51169245/58572084-b0ac1c80-8243-11e9-84bc-b9352cdaf389.png)

**Comment by oduvan** [comment]
fixed
